name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    services:
      pg:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: data_migration_test
          TZ: UTC
        ports:
          - 15435:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: data_migration_test
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 13306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
          MSSQL_SA_PASSWORD: StrongPassword!
        ports:
          - 11433:1433
        options: >-
          --health-cmd="/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StrongPassword!' -C -Q 'SELECT 1'"
          --health-interval 10s
          --health-retries 10
          --health-timeout 5s
          --health-start-period 10s

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          elixir-version: '1.18'
          otp-version: '27'

      - name: Restore deps
        id: restore-mix-deps
        if: ${{ !contains(github.event.*.labels.*.name, 'no-cache') }}
        uses: actions/cache/restore@v4
        env:
          cache-version: &cache-version v1
          cache-name: &cache-deps-name cache-deps
        with:
          path: &cache-deps-paths |
            deps
            ~/.hex
            ~/.mix
          key: &cache-deps-key ${{ env.cache-name }}-${{ env.cache-version }}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: &cache-deps-restore-keys |
            ${{ env.cache-name }}-${{ env.cache-version }}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-

      - name: Install deps
        id: deps
        run: rm mix.lock && mix deps.get --only test

      - name: Cache mix deps
        id: cache-deps
        uses: actions/cache/save@v4
        env:
          cache-version: *cache-version
          cache-name: *cache-deps-name
        with:
          path: *cache-deps-paths
          key: *cache-deps-key

      - name: mix compile
        id: compile
        run: mix compile --force --warnings-as-errors

      - name: mix format
        id: format
        run: mix format --check-formatted

      - run: ECTO_ADAPTER=sqlite mix test --warnings-as-errors
      - run: ECTO_ADAPTER=pg mix test --warnings-as-errors
      - run: ECTO_ADAPTER=myxql mix test --warnings-as-errors
      - run: ECTO_ADAPTER=tds mix test --warnings-as-errors

      - name: Restore PLTs
        uses: actions/cache/restore@v4
        id: restore-plts
        if: ${{ steps.compile.outcome == 'success' && !contains(github.event.*.labels.*.name, 'no-cache') }}
        env:
          cache-version: *cache-version
          cache-name: plt_cache
        with:
          path: &cache-plts-paths |
            priv/plts
          key: &cache-plts-key ${{ env.cache-name }}-${{ env.cache-version }}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('**/*.ex') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ env.cache-version }}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-${{ hashFiles('mix.lock') }}-
            ${{ env.cache-name }}-${{ env.cache-version }}-${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-

      - name: Create PLTs
        id: create-plts
        if: ${{ steps.restore-plts.outputs.cache-hit != 'true' }}
        run: mix dialyzer --plt

      - name: Cache PLTs
        uses: actions/cache/save@v4
        if: ${{ steps.create-plts.outcome == 'success' }}
        env:
          cache-version: *cache-version
          cache-name: plt_cache
        with:
          path: *cache-plts-paths
          key: *cache-plts-key

      - name: Run Dialyzer
        id: dialyzer
        run: mix dialyzer
